@startuml  強化の設計
hide empty members

Interface IEnhanceable
{
 Enhance()
}

class EnhanceSystem
{
  Enhance()
}

class EnahanceCommand
{
  Start()
  Execute()
  End()
  IsFinish()
}

EnahanceCommand o-- EnhanceSystem

SmithBattleMediator <-- Enhance
